version: '3.8'

services:
  # FastAPI应用 - 使用SQLite数据库
  app:
    build: .
    container_name: k12-share-platform
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./k12_share.db
      - UPLOAD_DIR=uploads
      - MAX_FILE_SIZE=52428800
      - DEBUG=false
      - APP_NAME=K12家校学习资料共享平台
    volumes:
      - ./uploads:/app/uploads
      - ./static:/app/static
      - ./k12_share.db:/app/k12_share.db
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
